=== cablelabs/siddhi-map-p4-trpt/docs/json/trpt_packet.schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "properties": {
    "telemRptHdr": {
      "type": "object",
      "properties": {
        "domainId": {
          "type": "integer"
        },
        "hardwareId": {
          "type": "integer"
        },
        "inType": {
          "type": "integer"
        },
        "nodeId": {
          "type": "integer"
        },
        "rptLen": {
          "type": "integer"
        },
        "seqNo": {
          "type": "integer"
        },
        "version": {
          "type": "integer"
        },
        "metaLen": {
          "type": "integer"
        },
        "rptType": {
          "type": "integer"
        },
        "d": {
          "type": "integer"
        },
        "q": {
          "type": "integer"
        },
        "f": {
          "type": "integer"
        },
        "i": {
          "type": "integer"
        },
        "repMdBits": {
          "type": "string"
        },
        "mdbBits": {
          "type": "string"
        },
        "mdsBits": {
          "type": "string"
        },
        "varOptMd": {
          "type": "string"
        }
      },
      "required": [
        "domainId",
        "hardwareId",
        "inType",
        "nodeId",
        "rptLen",
        "seqNo",
        "version",
        "metaLen",
        "rptType",
        "d",
        "q",
        "f",
        "i",
        "repMdBits",
        "mdbBits",
        "mdsBits",
        "varOptMd"
      ]
    },
    "intEthHdr": {
      "type": "object",
      "properties": {
        "dstMac": {
          "type": "string"
        },
        "srcMac": {
          "type": "string"
        },
        "type": {
          "type": "integer"
        }
      },
      "required": [
        "dstMac",
        "srcMac",
        "type"
      ]
    },
    "ipHdr": {
      "type": "object",
      "properties": {
        "len": {
          "type": "integer"
        },
        "nextProto": {
          "type": "integer"
        },
        "version": {
          "type": "integer"
        },
        "dstAddr": {
          "type": "string"
        },
        "srcAddr": {
          "type": "string"
        }
      },
      "required": [
        "len",
        "nextProto",
        "version",
        "dstAddr",
        "srcAddr"
      ]
    },
    "udpIntHdr": {
      "type": "object",
      "properties": {
        "srcPort": {
          "type": "integer"
        },
        "dstPort": {
          "type": "integer"
        },
        "len": {
          "type": "integer"
        }
      },
      "required": [
        "srcPort",
        "dstPort",
        "len"
      ]
    },
    "intHdr": {
      "type": "object",
      "properties": {
        "shimHdr": {
          "type": "object",
          "properties": {
            "type": {
              "type": "integer"
            },
            "npt": {
              "type": "integer"
            },
            "len": {
              "type": "integer"
            },
            "nextProto": {
              "type": "integer"
            }
          },
          "required": [
            "type",
            "npt",
            "len",
            "nextProto"
          ]
        },
        "mdHdr": {
          "type": "object",
          "properties": {
            "version": {
              "type": "integer"
            },
            "d": {
              "type": "integer"
            },
            "e": {
              "type": "integer"
            },
            "m": {
              "type": "integer"
            },
            "mdLen": {
              "type": "integer"
            },
            "remainingHopCount": {
              "type": "integer"
            },
            "instructions": {
              "type": "string"
            },
            "domainId": {
              "type": "integer"
            },
            "dsInstructions": {
              "type": "string"
            },
            "dsFlags": {
              "type": "string"
            }
          },
          "required": [
            "version",
            "d",
            "e",
            "m",
            "mdLen",
            "remainingHopCount",
            "instructions",
            "domainId",
            "dsInstructions",
            "dsFlags"
          ]
        },
        "mdStackHdr": {
          "type": "object",
          "properties": {
            "origMac": {
              "type": "string"
            },
            "hops": {
              "type": "array",
              "items": [
                {
                  "type": "integer"
                },
                {
                  "type": "integer"
                }
              ]
            }
          },
          "required": [
            "origMac",
            "hops"
          ]
        }
      },
      "required": [
        "shimHdr",
        "mdHdr",
        "mdStackHdr"
      ]
    },
    "protoHdr": {
      "type": "object",
      "properties": {
        "srcPort": {
          "type": "integer"
        },
        "dstPort": {
          "type": "integer"
        }
      },
      "required": [
        "srcPort",
        "dstPort"
      ]
    },
    "payload": {
      "type": "string"
    }
  },
  "required": [
    "telemRptHdr",
    "intEthHdr",
    "ipHdr",
    "udpIntHdr",
    "intHdr",
    "protoHdr",
    "payload"
  ]
}

=== cablelabs/siddhi-map-p4-trpt/docs/json/trpt_packet.example.json
{
  "telemRptHdr": {
    "domainId": 21587,
    "hardwareId": 13,
    "inType": 4,
    "nodeId": 234,
    "rptLen": 10,
    "seqNo": 1089,
    "version": 2,
    "metaLen": 8,
    "rptType": 0,
    "d": 0,
    "q": 1,
    "f": 0,
    "i": 1,
    "repMdBits": "0101010110101010",
    "mdbBits": "0101010110101010",
    "mdsBits": "1010101001010101",
    "varOptMd": "00000000000000000000000000000000"
  },
  "intEthHdr": {
    "dstMac": "00:00:00:00:05:01",
    "srcMac": "00:00:00:00:01:01",
    "type": 2048
  },
  "ipHdr": {
    "len": 94,
    "nextProto": 17,
    "version": 4,
    "dstAddr": "192.168.1.10",
    "srcAddr": "192.168.1.2"
  },
  "udpIntHdr": {
    "srcPort": 0,
    "dstPort": 555,
    "len": 74
  },
  "intHdr": {
    "shimHdr": {
      "type": 1,
      "npt": 2,
      "len": 8,
      "nextProto": 17
    },
    "mdHdr": {
      "version": 2,
      "d": 0,
      "e": 0,
      "m": 0,
      "mdLen": 1,
      "remainingHopCount": 9,
      "instructions": "1000000000000000",
      "domainId": 21587,
      "dsInstructions": "1000000000000000",
      "dsFlags": "0100000000000000"
    },
    "mdStackHdr": {
      "origMac": "00:00:00:00:01:01",
      "hops": [
        123,
        234
      ]
    }
  },
  "protoHdr": {
    "srcPort": 6680,
    "dstPort": 5792
  },
  "payload": "68656c6c6f207472616e73706172656e742d7365637572697479"
}
